### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by Pavelius** [Pavelius/eob2#5]
- [x] Show character name
- [x] Show character hit points
- [x] Use advance character by levels
- [x] Use start equipment lists. When we try find list of variants and add this one to inventory.
- [x] See magical
- [x] See cursed
- [x] See illusion
- [x] Protection from Evil
- [x] Blinking colors. For magic and for other effects.
- [x] Blinking item avatars in different colors. Depends this colors on activity of `See...` feats.
- [x] Remove collection and use answers.
- [x] Action object. Separate naming in menu. Condition for player use. Scripting use.
- [x] Scripting choose and apply. Name use prefix of parent list.
